osx_image: xcode10.2
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods --pre --no-document
- pod repo update
- pod install --project-directory=Example
script:
- xcodebuild -scheme UITextField_Navigation_Tests -workspace Example/UITextField-Navigation.xcworkspace -sdk iphonesimulator11.0 -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2' build test | xcpretty
- pod lib lint
after_success:
- bash <(curl -s https://codecov.io/bash) -J 'UITextField_Navigation'
